name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    # 1:30 (UTC) == 9:30 (UTC+8)
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        CONFIG: ${{ secrets.config }}
      run: |
        echo CONFIG > config.json
        python report.py
